"""System 2 Generative Model Providers (Hermes, Grok, Claude, etc.)."""

from __future__ import annotations
import os
import json
import time
import logging
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
import httpx

logger = logging.getLogger(__name__)


class SystemTwoResponse(BaseModel):
    """Output from System 2 reasoning/generative engine."""
    thought: str
    action: str
    args: Dict[str, Any] = Field(default_factory=dict)
    generated_content: Optional[str] = None
    latency_ms: float = 0.0
    tokens_used: int = 0


class SystemTwoProvider(ABC):
    """Abstract interface for System 2 fallback reasoners."""

    @abstractmethod
    def generate_step(self, prompt: str) -> SystemTwoResponse:
        """Process agent prompt and return thought, next action, and arguments."""
        pass


class MockSystemTwoProvider(SystemTwoProvider):
    """Simulated System 2 provider for testing and zero-config demonstration."""

    def generate_step(self, prompt: str) -> SystemTwoResponse:
        start = time.perf_counter()
        # Simulate ~300ms generative latency
        time.sleep(0.3)
        elapsed_ms = (time.perf_counter() - start) * 1000

        # Heuristic synthesis based on prompt content
        if "summary" in prompt.lower() or "count" in prompt.lower():
            thought = "Analyzed workspace data. Generating structured summary output."
            action = "finish_task"
            args = {"result": "Task completed successfully. Synthesized final analysis."}
            content = "Summary: All items analyzed and verified according to requirements."
        else:
            thought = "Synthesizing code script to achieve the stated goal."
            action = "write_file"
            args = {"path": "generated_script.py", "content": "# Generated by System 2\nprint('System 2 output')"}
            content = "Script generated."

        return SystemTwoResponse(
            thought=thought,
            action=action,
            args=args,
            generated_content=content,
            latency_ms=elapsed_ms,
            tokens_used=450,
        )


class HermesProvider(SystemTwoProvider):
    """Nous Research Hermes 3 provider via local Ollama or vLLM."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 30.0,
    ):
        self.base_url = base_url or os.getenv("HERMES_BASE_URL", "http://localhost:11434/v1")
        self.model = model or os.getenv("HERMES_MODEL", "nous-hermes-3-llama-3.1-8b")
        self.timeout = timeout

    def generate_step(self, prompt: str) -> SystemTwoResponse:
        start = time.perf_counter()
        try:
            with httpx.Client(timeout=self.timeout) as client:
                res = client.post(
                    f"{self.base_url.rstrip('/')}/chat/completions",
                    json={
                        "model": self.model,
                        "messages": [
                            {"role": "system", "content": "You are Hermes, an autonomous reasoning agent. Always output valid JSON with 'thought', 'action', and 'args'."},
                            {"role": "user", "content": prompt},
                        ],
                        "response_format": {"type": "json_object"},
                    },
                )
                res.raise_for_status()
                data = res.json()
                elapsed_ms = (time.perf_counter() - start) * 1000

                raw_content = data["choices"][0]["message"]["content"]
                parsed = json.loads(raw_content)
                tokens = data.get("usage", {}).get("total_tokens", 500)

                return SystemTwoResponse(
                    thought=parsed.get("thought", "Executed reasoning."),
                    action=parsed.get("action", "finish_task"),
                    args=parsed.get("args", {}),
                    generated_content=raw_content,
                    latency_ms=elapsed_ms,
                    tokens_used=tokens,
                )
        except Exception as e:
            logger.warning(f"Hermes provider failed ({e}). Falling back to mock response.")
            mock = MockSystemTwoProvider()
            return mock.generate_step(prompt)


class OpenAICompatibleProvider(SystemTwoProvider):
    """Provider for xAI Grok, OpenAI, or any OpenAI-compatible API."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 30.0,
    ):
        self.api_key = api_key or os.getenv("GROK_API_KEY") or os.getenv("OPENAI_API_KEY", "")
        self.base_url = base_url or os.getenv("OPENAI_BASE_URL", "https://api.x.ai/v1" if "GROK" in os.environ else "https://api.openai.com/v1")
        self.model = model or os.getenv("GROK_MODEL", "grok-2-latest" if "GROK" in os.environ else "gpt-4o")
        self.timeout = timeout

    def generate_step(self, prompt: str) -> SystemTwoResponse:
        start = time.perf_counter()
        if not self.api_key:
            logger.warning("No API key found for OpenAICompatibleProvider. Falling back to mock.")
            return MockSystemTwoProvider().generate_step(prompt)

        try:
            with httpx.Client(timeout=self.timeout) as client:
                res = client.post(
                    f"{self.base_url.rstrip('/')}/chat/completions",
                    headers={"Authorization": f"Bearer {self.api_key}"},
                    json={
                        "model": self.model,
                        "messages": [
                            {"role": "system", "content": "You are a deliberate System 2 agent. Return valid JSON: {'thought': '...', 'action': '...', 'args': {...}}"},
                            {"role": "user", "content": prompt},
                        ],
                        "response_format": {"type": "json_object"},
                    },
                )
                res.raise_for_status()
                data = res.json()
                elapsed_ms = (time.perf_counter() - start) * 1000

                raw = data["choices"][0]["message"]["content"]
                parsed = json.loads(raw)
                tokens = data.get("usage", {}).get("total_tokens", 450)

                return SystemTwoResponse(
                    thought=parsed.get("thought", "Completed deliberate reasoning."),
                    action=parsed.get("action", "finish_task"),
                    args=parsed.get("args", {}),
                    generated_content=raw,
                    latency_ms=elapsed_ms,
                    tokens_used=tokens,
                )
        except Exception as e:
            logger.warning(f"System 2 API call failed: {e}. Falling back to mock.")
            return MockSystemTwoProvider().generate_step(prompt)


def get_system_two_provider(provider_type: Optional[str] = None) -> SystemTwoProvider:
    """Factory function to resolve configured System 2 provider."""
    ptype = (provider_type or os.getenv("SYSTEM_TWO_PROVIDER", "mock")).lower()
    
    if ptype in ("hermes", "hermes_ollama", "ollama"):
        return HermesProvider()
    elif ptype in ("grok", "xai"):
        return OpenAICompatibleProvider(
            base_url="https://api.x.ai/v1",
            model=os.getenv("GROK_MODEL", "grok-2-latest"),
            api_key=os.getenv("GROK_API_KEY"),
        )
    elif ptype in ("openai", "gpt"):
        return OpenAICompatibleProvider()
    else:
        return MockSystemTwoProvider()
